In [1]:
import numpy as np

In [160]:
a = np.random.rand(3, 4)

In [172]:
a

array([[ 0.14607367,  0.7287508 ,  0.12464141,  0.47584852],
       [ 0.79388835,  0.85745085,  0.01851124,  0.57700308],
       [ 0.90145894,  0.61696037,  0.66184084,  0.10052933]])

In [174]:
aa = np.array([1,2,3])

In [176]:
np.sum(a, axis=1)

array([ 1.4753144 ,  2.24685353,  2.28078948])

In [173]:
a * np.array([1,2,3])

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [139]:
b = np.random.rand(5, 4)

In [171]:
c = np.array([1,2,3,4])
np.tile(c, (4,1)).T

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4]])

In [141]:
x = np.array([1,2,3])


array([[ 0.32287262,  0.17783577,  0.85354375,  0.26730401],
       [ 0.31485601,  0.12651821,  0.70514784,  0.60017966],
       [ 0.26016001,  0.16295248,  0.86661971,  0.4665722 ],
       [ 0.85925079,  0.47977986,  0.57436165,  0.66126623],
       [ 0.35546365,  0.51516211,  0.63946348,  0.32037416]])

In [151]:
c = np.array([0.3, 0.1])

In [155]:
np.array(b[0:2,:] < c[:, np.newaxis], dtype=np.uint8)

array([[0, 1, 0, 1],
       [0, 0, 0, 0]], dtype=uint8)

In [5]:
a - b

ValueError: operands could not be broadcast together with shapes (3,4) (5,4) 

In [11]:
c = np.random.rand(1,4)

In [24]:
e = np.zeros(3, 4, 5)

TypeError: data type not understood

In [25]:
for i in xrange(a.shape[0]):
    e[i, :] = a[i, :] - b

In [32]:
e2 = e.reshape(3, 4, 5)

In [29]:
np.linalg.norm(e, axis=2)

array([[ 0.71231184,  0.70618134,  0.84134655,  0.86510603,  0.82949715],
       [ 1.06825128,  0.94050583,  0.64569943,  0.99011669,  0.74146275],
       [ 1.25652876,  1.03595112,  0.28043616,  0.76869755,  0.70494657]])

In [33]:
e * e2

ValueError: operands could not be broadcast together with shapes (3,5,4) (3,4,5) 

In [35]:
ab = a.dot(np.transpose(b))

In [40]:
a2 = np.sum(a ** 2, axis = 1)
a2.shape

(3,)

In [44]:
b2 = np.sum(b ** 2, axis = 1)

In [100]:
dists = b2 - 2*ab + np.matrix(a2).T

In [103]:
np.array(dists)

array([[ 0.50738816,  0.49869209,  0.70786401,  0.74840845,  0.68806551],
       [ 1.14116079,  0.88455122,  0.41692776,  0.98033106,  0.54976701],
       [ 1.57886452,  1.07319473,  0.07864444,  0.59089592,  0.49694966]])

In [106]:
np.array(np.argsort(dists[0,:]))[0,:]

array([1, 0, 4, 2, 3])

In [78]:
x = np.array([1,2,3,1,2,1,1,1,3,2,2,1])

In [79]:
np.bincount(x)

array([0, 6, 4, 2])

In [66]:
np.bincount(np.array([0, 1, 1, 3, 2, 1, 7]))

array([1, 3, 1, 1, 0, 0, 0, 1])

In [80]:
y = []

In [83]:
y = x[:3]

In [84]:
y

array([1, 2, 3])

In [85]:
b[0,:]

array([ 0.9632034 ,  0.00518694,  0.57054063,  0.01666793])

In [107]:
min(2,3)

2

In [132]:
a = np.arange(10)
a_folds = np.array_split(a, 3)

In [128]:
a_folds[1]= np.ma.masked

In [129]:
a_folds


[array([0, 1, 2, 3]), masked, array([7, 8, 9])]

In [134]:
np.concatenate([a_folds[i] for i in range(3) if i != 1])

array([0, 1, 2, 3, 7, 8, 9])

In [135]:
a = np.array([1,2,3])

In [136]:
np.transpose(a)

array([1, 2, 3])

In [137]:
b


In [138]:
b

In [156]:
a = np.array([1,2,1])

In [158]:
1 - (np.arange(3) == a[:, None]).astype(np.float32)

array([[ 1.,  0.,  1.],
       [ 1.,  1.,  0.],
       [ 1.,  0.,  1.]], dtype=float32)